ALARM_RING_SECONDS = 60
DEFAULT_RING_COUNT = 5
MAX_RING_COUNT = 20
DEFAULT_SNOOZE_MINUTES = 5
MIN_SNOOZE_MINUTES = 1
MAX_SNOOZE_MINUTES = 120
MIN_RING_DURATION_SECONDS = 5
MAX_RING_DURATION_SECONDS = 600

WEEKDAY_NAMES = ("Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun")
